namespace: hms-prod
replicaCount: 1
image:
  repository: ghcr.io/hospitalmanagementsystem-hms/api-gateway
  tag: stable
  pullPolicy: Always
service:
  type: ClusterIP
  port: 4000
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  PORT: "4000"
  SERVICE_NAME: "api-gateway"
secrets:
  JWT_SECRET: "prod_super_secret_jwt_key_2024"
  INTERNAL_API_KEY: "prod_internal_key"
