# appointment-service deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: suryaa112003/appointment-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: TZ
          value: "Asia/Kolkata"
        - name: MONGO_URI
          value: "mongodb://admin:admin123@mongodb:27017/hms_appointment?authSource=admin"
        - name: MONGO_DB_NAME
          value: "hms_appointment"
        - name: JWT_SECRET
          value: "super_secure_jwt_secret_123"
        - name: INTERNAL_API_KEY
          value: "dev_internal_key_change_me"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:5000"
        - name: USER_SERVICE_URL
          value: "http://user-service:5001"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:5004"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:4000"
---
# appointment-service service.yaml
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: ClusterIP
  selector:
    app: appointment-service
  ports:
  - port: 5002
    targetPort: 5002
