# notification-service deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: suryaa112003/notification-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: TZ
          value: "Asia/Kolkata"
        - name: MONGO_URI
          value: "mongodb://admin:yourSecurePassword@mongodb:27017/?authSource=admin"
        - name: MONGO_DB_NAME
          value: "hms_notification"
        - name: JWT_SECRET
          value: "super_secure_jwt_secret_123"
        - name: INTERNAL_API_KEY
          value: "dev_internal_key_change_me"
        - name: MED_REMINDER_TZ
          value: "UTC"
        - name: FOLLOW_UP_POLL_SECONDS
          value: "60"
        - name: EMAIL_USER
          value: "example@gmail.com"
        - name: EMAIL_PASS
          value: "app_password"
---
# notification-service service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - port: 5004
    targetPort: 5004
