# user-service deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: suryaa112003/user-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: TZ
          value: "Asia/Kolkata"
        - name: MONGO_URI
          value: "mongodb://admin:admin123@mongodb:27017/?authSource=admin"
        - name: MONGO_DB_NAME
          value: "hms_user"
        - name: JWT_SECRET
          value: "super_secure_jwt_secret_123"
        - name: INTERNAL_API_KEY
          value: "dev_internal_key_change_me"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:5000"
        - name: APPOINTMENT_SERVICE_URL
          value: "http://appointment-service:5002"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:5004"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:4000"
---
# user-service service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - port: 5001
    targetPort: 5001
