apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  JWT_SECRET: "super_secure_jwt_secret_123_change_me_in_prod"
  INTERNAL_API_KEY: "dev_internal_key_change_me_in_prod"
