namespace: hms-prod
replicaCount: 1
image:
  repository: ghcr.io/hospitalmanagementsystem-hms/appointment-service
  tag: v1.1.0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5002
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  PORT: "5002"
  SERVICE_NAME: "appointment-service"
secrets:
  JWT_SECRET: "prod_super_secret_jwt_key_2024"
  INTERNAL_API_KEY: "prod_internal_key"
