namespace: hms-dev
replicaCount: 1
image:
  repository: suryaa112003/appointment-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5002
  
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  PORT: "5002"
  SERVICE_NAME: "appointment-service"
secrets:
  JWT_SECRET: "dev_secret_123"
  INTERNAL_API_KEY: "dev_internal_key"
