namespace: hms-dev
replicaCount: 1
image:
  repository: suryaa112003/frontend
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 3000
  nodePort: 30080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  PORT: "3000"
  SERVICE_NAME: "frontend"
secrets:
  JWT_SECRET: "dev_secret_123"
  INTERNAL_API_KEY: "dev_internal_key"
