namespace: hms-prod
replicaCount: 1
image:
  repository: ghcr.io/hospitalmanagementsystem-hms/user-service
  tag: v1.1.1
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5001
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  PORT: "5001"
  SERVICE_NAME: "user-service"
secrets:
  JWT_SECRET: "prod_secret_123"
  INTERNAL_API_KEY: "prod_internal_key"
